name: dps_school
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.5
  dio: ^5.1.1
  shared_preferences: ^2.1.0
  intl: ^0.17.0
  get: ^4.6.5
  connectivity_plus: ^3.0.4
  flutter_secure_storage: ^8.0.0
  shimmer: ^2.0.0
  sqflite: ^2.2.6
  path: ^1.8.2
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/pngs/

  # To add assets to your application, add an assets section, like this:
  fonts:
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFPRODISPLAYREGULAR.ttf
          weight: 400
        - asset: assets/fonts/SFPRODISPLAYMEDIUM.ttf
          weight: 500
        - asset: assets/fonts/SFPRODISPLAYBOLD.ttf
          weight: 700
